server:
  port: 8030
spring:  application:    name: config-server
  cloud:    config:      label: master
      server:        git:          uri: https://github.com/xgl123456/SpringcloudConfig/
          search-paths:          - respo
          
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka